name: Build Android Debug APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Signing steps are removed for debug build

    - name: Build with Buildozer
      working-directory: ./webview_app
      run: |
        buildozer -v android debug
      # No signing environment variables needed for debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webview-app-debug-apk
        path: webview_app/bin/*.apk

    - name: Upload Build Log Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildozer-log
        path: webview_app/.buildozer/buildozer.log
