name: Build Android Debug APK with DroidBuilder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 4. Install APT dependencies (if needed by your project)
      - name: Install APT prerequisites
        run: |
          sudo apt-get update
          # sudo apt-get install -y $(grep -vE '^\s*#' prerequisites.txt | tr '\n' ' ')

      # 5. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Initialize DroidBuilder environment (optional)
      - name: Initialize DroidBuilder
        run: |
          droidbuilder init
          python - <<EOF
          import toml, os
          config = {
              "project": {
                  "name": os.getenv("PROJECT_NAME", "Browser"),
                  "version": os.getenv("APP_VERSION", "1.0.0"),
                  "main_file": "main.py"
              },
              "android": {
                  "sdk_version": os.getenv("ANDROID_SDK_VERSION", "36"),
                  "ndk_version": os.getenv("ANDROID_NDK_VERSION", "28.2.13676358"),
                  "build_type": os.getenv("BUILD_TYPE", "debug")
              },
              "java": {
                  "jdk_version": os.getenv("JAVA_JDK_VERSION", "21")
              }
          }
          with open("droidbuilder.toml", "w") as f:
              toml.dump(config, f)
          EOF
        env:
          PROJECT_NAME: ${{ github.event.repository.name }}
          APP_VERSION: 1.0.${{ github.run_number }}
          ANDROID_SDK_VERSION: 36
          ANDROID_NDK_VERSION: 28.2.13676358
          JAVA_JDK_VERSION: 21
          BUILD_TYPE: debug

      # 7. Clean previous builds
      - name: Clean previous builds
        run: |
          droidbuilder clean || true

      # 8. Build APK
      - name: Build Debug APK
        run: |
          droidbuilder install-tools --ci
          droidbuilder build android --mode debug --verbose

      # 9. Upload APK Artifact
      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: webview-app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
