name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/kmedya-dev/droidbuilder.git@main
        droidbuilder install-tools
