name: Build Android Debug APK with DroidBuilder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 4. Install APT dependencies (if needed by your project)
      - name: Install APT prerequisites
        run: |
          sudo apt-get update
          # sudo apt-get install -y $(grep -vE '^\s*#' prerequisites.txt | tr '\n' ' ')

      # 5. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Clean previous builds
      - name: Clean previous builds
        run: |
          set -x
          droidbuilder clean

      # 7. Build APK
      - name: Build Debug APK
        run: |
          set -x
          droidbuilder install-tools --ci
          droidbuilder build android

      # 8. Upload APK Artifact
      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: webview-app-debug-apk
          path: bin/*.apk
